name: flexserviceflutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  font_awesome_flutter: ^9.1.0
  
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7

  shared_preferences: ^2.0.5

  google_fonts: ^2.1.0
  connectivity: ^3.0.6

  flushbar: ^1.10.4
  persistent_bottom_nav_bar: ^4.0.2
  geolocator: 7.6.2
  dotted_border: ^2.0.0+1
  multi_select_flutter: ^4.0.0
  url_launcher: ^6.0.10
  google_maps_flutter: ^2.0.9
  
  flutter_typeahead: ^3.2.1

  date_time_picker: ^2.1.0

  flutter_local_notifications: ^9.0.0
  image_picker: ^0.8.4
  
  syncfusion_flutter_signaturepad: ^19.3.44
  data_connection_checker: ^0.3.4
  signature: ^4.1.1
  data_table_2: ^2.1.1
  flutter_svg: ^0.22.0
  flutter_native_splash: ^1.2.0

dev_dependencies:
 
  # change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/service.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
